version: '3.3'
services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'loginData'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3306:3306'
    expose:
      - 3306
    networks:
      - my-network
    volumes:
      - my-db:/var/lib/mysql
  back:
    depends_on:
      - db
    build: ./LoginService
    restart: always
    ports:
      - '8000:8000'
    expose:
      - 8000
    networks:
      - my-network
    stdin_open: true
    tty: true
  front:
    depends_on:
      - back
    build: ./proyectoZapping
    restart: always
    ports:
      - '3000:3000'
    expose:
      - 3000
    networks:
      - my-network
    stdin_open: true
    tty: true
networks:
    my-network:
volumes:
  my-db: